# MariaDB
version: "3.7"
services:
  database:
    #image: mariadb
    container_name: xlp_mariadb
    image: xlp0/mariadb
    # platform: linux/amd64
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
    #command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --innodb-force-recovery=1
    environment:
      #entrypoint: mysqld_safe --skip-grant-tables --user=root
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      # data file location
      - ./mountpoint/mariadb:/var/lib/mysql
      # backup and restore file location
      - ./mountpoint/backup_restore/mariadb:/mnt/backup_restore/mariadb
      # entry point
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports: 
     - 3306:3306
  mediawiki:
    # default username/password: admin/admin_on_d0cker
    image: xlp0/semanticwiki
    container_name: xlp_mediawiki
    # platform: linux/amd64
    restart: always
    ports:    
    - ${PORT_NUMBER}:80
    links:
    - database
    volumes:
    # images file location
    - ./mountpoint/images:/var/www/html/images
    # backup and restore file location
    - ./mountpoint/backup_restore/mediawiki:/mnt/backup_restore/mediawiki
    # Following the default MediaWiki installation process, it will first assume that there is no LocalSettings.php in the 
    # default location, in this case, /var/www/html/. However, after going through the installation procedure that collects information from 
    # the installation person from a browser, the system will generate a LocalSettings.php, and it should be placed in /var/www/html/.
    # For convenience, the following long line is a reminder for the procedure: It is recommended to comment out the following line 
    # when first install a "fresh" instance of MediaWiki. This statement exclude the situation when one just want to use the default mountPoint content as the fresh data set.
    - ./mountpoint/LocalSettings.php:/var/www/html/LocalSettings.php
    - ./backup/xml:/var/www/html/backup
    depends_on:
    - database
  matomo:
    # default username/password: user/bitnami
    image: docker.io/bitnami/matomo:4
    # image: matomo:4.4.1-fpm
    # image: matomo:4.4.1-apache
    container_name: xlp_matomo
    ports:
    - ${MATOMO_PORT_NUMBER}:8080
    - "443:8443"
    environment:
    - MATOMO_DATABASE_HOST=database
    - MATOMO_DATABASE_PORT_NUMBER=3306
    - MATOMO_DATABASE_USER=root
    - MATOMO_DATABASE_NAME=matomo
    - MATOMO_DATABASE_PASSWORD=secret
    - ALLOW_EMPTY_PASSWORD=no
    volumes:
    - "./mountpoint/matomo:/bitnami/matomo"
    depends_on:
    - database
    links:
    - database
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - MYSQL_ROOT_PASSWORD=secret
    - PMA_HOST=database
    - UPLOAD_LIMIT=123M
    - MAX_EXECUTION_TIME=125
    - HIDE_PHP_VERSION= 1
    restart: always
    ports:
     - ${PHP_MA}:80
    volumes:
     - /sessions
  gitea:
    image: gitea/gitea:1.15.2
    container_name: xlp_gitea
    environment:
    - USER_UID=1000
    - USER_GID=1000
    - GITEA__database__DB_TYPE=mysql
    - GITEA__database__HOST=database:3306
    - GITEA__database__NAME=gitea
    - GITEA__database__USER=gitea
    - GITEA__database__PASSWD=gitea-pass
    restart: always
    volumes:
    - ./mountpoint/gitea:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    ports:
    - ${GITEA_PORT_NUMBER}:3000
    - "222:22"
    depends_on:
    - database
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: xlp_vs
    environment:
      - PUID=1000
      - PGID=1000
      - PASSWORD=xlp_vs #optional
      - SUDO_PASSWORD=password #optional
    volumes:
      - ./mountpoint/vs/config:/config
    ports:
      - ${VS_PORT_NUMBER}:8443
    restart: unless-stopped