apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanslate-app
spec:
  selector:
    matchLabels:
      app: cleanslate-app
  replicas: 1
  template:
    metadata:
      labels:
        app: cleanslate-app
    spec:
      containers:
        - name: cleanslate-container
          image: xlp0/semanticwiki
          volumeMounts:
            - mountPath: /var/www/html/images
              name: cleanslate-volume
            - mountPath: /var/www/html/LocalSettings.php
              name: cleanslate-localsettings
            - mountPath: /var/www/html/images_restore
              name: cleanslate-restore
            - mountPath: /var/www/html/images_backup
              name: cleanslate-backup
          ports:
            - containerPort: 80
      volumes:
        - name: cleanslate-volume
          persistentVolumeClaim:
            claimName: media-pv-claim
        - name: cleanslate-localsettings
          hostPath:
            path: /home/ubuntu/mount/LocalSettings.php
            type: File
        - name: cleanslate-restore
          hostPath:
            path: /efs/mount/mediawiki/images_restore/MediaFiles
        - name: cleanslate-backup
          persistentVolumeClaim:
            claimName: backup-media-pv-claim