apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-restore-db
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: restore-db-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-restore-db
  local:
    path: /home/ec2-user/mount/restore/mariadb      ## user-name
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-192-168-30-224.us-west-2.compute.internal
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: restore-db-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: sc-restore-db
  resources:
    requests:
      storage: 2Gi