# MariaDB

version: "3.7"
services:
  database:
    image: mariadb
    platform: linux/amd64
    restart: always
    environment:
      #entrypoint: mysqld_safe --skip-grant-tables --user=root
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mountPoint/mariadb:/var/lib/mysql
      - ./backup/mariadb:/home/
    #ports: 
    # - 3306:3306
  mediawiki:
    image: mediawiki
    platform: linux/amd64
    restart: always
    ports:
    - ${PORT_NUMBER}:80
    links:
    - database
    volumes:
    - ./mountPoint/images:/var/www/html/images
    # Following the default MediaWiki installation process, it will first assume that there is no LocalSettings.php in the 
    # default location, in this case, /var/www/html/. However, after going through the installation procedure that collects information from 
    # the installation person from a browser, the system will generate a LocalSettings.php, and it should be placed in /var/www/html/.
    # For convenience, the following long line is a reminder for the procedure: It is recommended to comment out the following line when first install a "fresh" instance of MediaWiki. This statement exclude the situation when one just want to use the default mountPoint content as the fresh data set.
    - ./LocalSettings.php:/var/www/html/LocalSettings.php
    - ./backup/xml:/var/www/html/backup
    depends_on:
    - database
  
  
